server:
  port: 8086
spring:
  datasource:
    #Here mysqlservice is the container name given in docker-compose file
    #url: jdbc:mysql://mysqlservice:3306/registered_users?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/registered_users?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: password
    #password: root
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: user-authentication-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true